### ISSUE TITLE
滚动条美化

### ISSUE THREAD

**Issue by TChenQuan** [ihewro/typecho-theme-handsome#21]
## 代码
```css
::-webkit-scrollbar,::-webkit-scrollbar-track {
	background-color: hsla(0,0%,100%,0)
	}
::-webkit-scrollbar {
	width: 6px
}
::-webkit-scrollbar-thumb {
	border-radius: 3px;
	background-color: #c1c1c1
}
```
